-- MySQL Script generated by MySQL Workbench
-- Thu Nov  9 16:09:52 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE =
        'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema p2_php
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema p2_php
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `p2_php` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE `mydb`;

-- -----------------------------------------------------
-- Table `p2_php`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `p2_php`.`users`
(
    `id`         INT          NOT NULL AUTO_INCREMENT,
    `nome`       VARCHAR(255) NOT NULL,
    `email`      VARCHAR(255) NOT NULL,
    `senha`      VARCHAR(400) NOT NULL,
    `created_at` TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
)
    ENGINE = InnoDB
    AUTO_INCREMENT = 30
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`compromissos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`compromissos`
(
    `id`         INT          NOT NULL AUTO_INCREMENT,
    `nome`       VARCHAR(100) NOT NULL,
    `local`      VARCHAR(100) NULL,
    `data`       DATE         NULL,
    `hora`       TIME         NULL,
    `created_at` TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `user_id`    INT          NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_compromissos_users_idx` (`user_id` ASC) VISIBLE,
    CONSTRAINT `fk_compromissos_users`
        FOREIGN KEY (`user_id`)
            REFERENCES `p2_php`.`users` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB
    COMMENT = '	';

USE `p2_php`;

-- -----------------------------------------------------
-- Table `p2_php`.`listas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `p2_php`.`listas`
(
    `id`         INT         NOT NULL AUTO_INCREMENT,
    `titulo`     VARCHAR(50) NOT NULL,
    `user_id`    INT         NOT NULL,
    `created_at` TIMESTAMP   NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP   NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX `user_id` (`user_id` ASC) VISIBLE,
    CONSTRAINT `listas_ibfk_1`
        FOREIGN KEY (`user_id`)
            REFERENCES `p2_php`.`users` (`id`)
)
    ENGINE = InnoDB
    AUTO_INCREMENT = 105
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `p2_php`.`itens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `p2_php`.`itens`
(
    `id`         INT          NOT NULL AUTO_INCREMENT,
    `nome`       VARCHAR(300) NOT NULL,
    `status`     TINYINT(1)   NOT NULL DEFAULT false,
    `lista_id`   INT          NOT NULL,
    `created_at` TIMESTAMP    NULL     DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP    NULL     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX `lista_id` (`lista_id` ASC) VISIBLE,
    CONSTRAINT `itens_ibfk_1`
        FOREIGN KEY (`lista_id`)
            REFERENCES `p2_php`.`listas` (`id`)
)
    ENGINE = InnoDB
    AUTO_INCREMENT = 139
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
